# Generated by Django 5.1.4 on 2025-03-03 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0002_remove_frameuserdata_client_id_clientinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaForWebExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_video', models.FileField(upload_to='web_videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='MediaData',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='video',
        ),
        migrations.AlterField(
            model_name='frameuserinfo',
            name='consumer_unique_id',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='mediaforwebexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameuser', to='framechanger.frameuserinfo'),
        ),
    ]
