# Generated by Django 5.1.4 on 2025-04-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0002_clientinfo_contactform_framecount_framepayment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactUs',
        ),
    ]
