# Generated by Django 5.1.4 on 2025-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0003_mediaforwebexperience_delete_mediadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='client_unique_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
