# Generated by Django 5.1.4 on 2025-04-15 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0003_rename_contactform_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framepayment',
            name='paid_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
