# Generated by Django 5.1.4 on 2025-03-05 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0004_alter_clientinfo_client_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='joined_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
