# Generated by Django 5.1.4 on 2025-03-05 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0005_alter_clientinfo_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameuserinfo',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
