# Generated by Django 5.1.4 on 2025-03-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0006_alter_frameuserinfo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='image',
        ),
    ]
