# Generated by Django 5.1.4 on 2025-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0008_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfo',
            name='client_unique_id',
        ),
        migrations.RemoveField(
            model_name='frameuserinfo',
            name='consumer_unique_id',
        ),
        migrations.AddField(
            model_name='frameuserinfo',
            name='pin_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
