# Generated by Django 5.1.4 on 2025-03-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framechanger', '0009_remove_clientinfo_client_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_count', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientid', to='framechanger.clientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='FramePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_id', models.CharField(max_length=30)),
                ('razorpay_order_id', models.CharField(max_length=30)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientassid', to='framechanger.clientinfo')),
            ],
        ),
    ]
